import { executeQuery } from "@lib/datocms";
import { buildFullPath, buildFullPathInsights } from "@utils/pathHelper";
import { AllLinkQuery } from "@utils/query";
import fs from "fs";
import path from "path";

const OUTPUT_PATH = "src/data/linkMap.ts";

async function run() {
  console.log("Link map generation...");
  const data = await executeQuery(AllLinkQuery);

  const linkMap: Record<string, Record<string, string>> = {};

  const home = data.homepage;
  if (home) {
    linkMap[home.id] = {};
    home.locales.forEach((locale) => {
      linkMap[home.id][locale] = `/${locale}`;
    });
  }

  data.allPages?.forEach((page) => {
    linkMap[page.id] = {};
    page.allSlugLocales?.forEach((item) => {
      const prefix = `/${item.locale}`;
      const slug = `/${item.value}`;
      if (!item.locale) return;
      linkMap[page.id][item.locale] = `${prefix}${slug}`;
    });
  });

  data.allArticles?.forEach((article) => {
    linkMap[article.id] = {};
    article.locales.forEach((locale) => {
      const fullPath = buildFullPath(article, locale, data.allArticles);
      const prefix = `/${locale}`;
      linkMap[article.id][locale] = `${prefix}/${fullPath}`;
    });
  });

  data.allInsights?.forEach((insight) => {
    linkMap[insight.id] = {};
    insight.locales.forEach((locale) => {
      const fullPath = buildFullPathInsights(insight, locale);
      const prefix = `/${locale}`;
      linkMap[insight.id][locale] = `${prefix}/${fullPath}`;
    });
  });

  const fileContent = `/**
* THIS FILE IS AUTOMATICALLY GENERATED
* DO NOT EDIT MANUALLY.
* * To update this file, run: "bun run generate:links"
* This map is generated from DatoCMS data during the build process.
*/

export const linkMap = ${JSON.stringify(linkMap, null, 2)};

export type LinkMap = typeof linkMap;
export type RecordId = keyof LinkMap;

export function linkResolver(id: string | undefined, locale: string): string {
    if (!id || !(id in linkMap)) {
        return '#';
    }
    return (linkMap[id as RecordId] as Record<string, string>)[locale] || '#';
}
`;

  const fullOutputPath = path.resolve(OUTPUT_PATH);
  if (!fs.existsSync(path.dirname(fullOutputPath)))
    fs.mkdirSync(path.dirname(fullOutputPath), { recursive: true });

  fs.writeFileSync(fullOutputPath, fileContent);
  console.log(`Link Map successfully generated at: ${OUTPUT_PATH}`);
}

run();
