export enum DatoBlockModel {
  Hero = "HeroRecord",
  NewsFeed = "NewsFeedRecord",
  SupportChannels = "SupportChannelsSectionRecord",
  FaqSection = "FaqSectionRecord",
  DataSection = "DataSectionRecord",
  UseCaseContainer = "UseCaseContainerRecord",
  TopicFilter = "TopicFilterRecord",
  SupportCta = "SupportCtaSectionRecord",
  StructuredText = "StructuredTextRecord",
  ListCollection = "ListCollectionRecord",
  CatalogueFeed = "CatalogueFeedRecord",
  ActionCard = "ActionCardRecord",
  SearchBar = "SearchBarRecord",
  TextImage = "TextImageRecord",
  TextStatistic = "TextStatisticRecord",
  TextUseCase = "TextUseCaseRecord",
  TextAccordion = "TextAccordionRecord",
  WebinarDescription = "WebinarDescriptionRecord",
  Speaker = "SpeakerRecord",
  IntroArticle = "IntroArticleRecord",
  CalloutLink = "CalloutLinkRecord",
  ListCardEditorial = "ListCardEditorialWithIconRecord",
  ExternalLink = "ExternalLinkRecord",
  OrderedList = "OrderedListRecord",
  Callout = "CalloutRecord",
  QuickLinkCard = "QuickLinkCardRecord",
  TopicsBlock = "TopicsBlockRecord",
  ListCardInfo = "ListCardInfoRecord",
  ListBlockquote = "ListBlockquoteRecord",
  RelatedArticle = "RelatedArticleRecord",
  ImageBlock = "ImageBlockRecord",
  NewsTab = "NewsTabRecord",
  StoryTab = "StoryTabRecord",
  ArticleNavigation = "ArticleNavigationRecord",
  ArticleList = "ArticleListRecord",
  InternalLink = "InternalLinkRecord",
  DownloadLink = "DownloadLinkRecord",
  AuthorList = "AuthorListRecord",
  IconListBlock = "IconListBlockRecord",
  AccordionBlock = "AccordionBlockRecord",
  StatisticBlock = "StatisticBlockRecord",
  UseCaseBlock = "UseCaseBlockRecord",
  TextBlock = "TextBlockRecord",
}

export type DatoBlockModelType =
  (typeof DatoBlockModel)[keyof typeof DatoBlockModel];
